# Generated by Django 4.0.5 on 2022-09-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='github_link',
            field=models.URLField(default='#', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='twiter_link',
            field=models.URLField(default='#', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='website_link',
            field=models.URLField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='facebook_link',
            field=models.URLField(default='#', max_length=100, null=True),
        ),
    ]
