# Generated by Django 4.0.5 on 2022-09-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userdetails_github_link_userdetails_twiter_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
