# Generated by Django 4.0.5 on 2022-09-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_userdetails_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
