# Generated by Django 4.0.5 on 2022-09-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_userdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
