# Generated by Django 4.0.5 on 2022-09-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userdetails_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
