# Generated by Django 4.0.5 on 2022-09-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='type',
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.ManyToManyField(to='portfolio.skillstype'),
        ),
    ]
