# Generated by Django 4.0.5 on 2022-09-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_skills_type_skills_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='type',
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.skillstype'),
        ),
    ]
