# Generated by Django 4.0.5 on 2022-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_name_skillstype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=10)),
            ],
        ),
    ]
