# Generated by Django 4.0.5 on 2022-09-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_whatido_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='VertionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.vertioncolor')),
            ],
        ),
    ]
