# Generated by Django 4.0.5 on 2022-09-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_vertioncolor_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vertioncolor',
            old_name='color',
            new_name='vertion',
        ),
    ]
