# Generated by Django 4.0.5 on 2022-09-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_color_vertioncolor_vertion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.allcolor'),
        ),
    ]
