# Generated by Django 4.0.5 on 2022-09-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_category_pricetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
