# Generated by Django 4.0.5 on 2022-09-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_pricetable_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('button_text', models.CharField(max_length=50)),
                ('demo_link', models.URLField(default='#', max_length=100)),
                ('thumbnail_image', models.ImageField(null=True, upload_to='thumbnail/')),
                ('category', models.ManyToManyField(to='portfolio.category')),
                ('skils', models.ManyToManyField(to='portfolio.skillstype')),
            ],
        ),
    ]
