# Generated by Django 4.0.5 on 2022-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skils',
            field=models.ManyToManyField(to='portfolio.skills'),
        ),
    ]
