# Generated by Django 4.0.5 on 2022-09-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_project_skils'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(null=True, upload_to='blog/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='blog_image',
            field=models.ManyToManyField(to='portfolio.blogimage'),
        ),
    ]
