# Generated by Django 4.0.5 on 2022-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_userdetails_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cv_file',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
